### ISSUE TITLE
Code repetition while encoding nested messages

### ISSUE THREAD

**Issue by burzomir** [anmolitor/protoc-gen-elm#331]
I'd like to introduce alternate constructors to reduce number of lines required to create and encode a message.

Example .proto
```
message ParentMessage {
  oneof msg {
    ChildMessage ChildMessage = 1
  }
}

message ChildMessage {
  oneof msg {
    GrandChildMessage GrandChildMessage = 1
  }
}

message GrandChildMessage = {}
```

How I currently have to structure my code:

```
{}
        |> grandChildMessage
        |> (\msg_ -> { msg = Just msg_ })
        |> childMessage
        |> (\msg_ -> { msg = Just msg_ })
        |> encodeParentMessage
```

How I would like to structure my code:

```
{}
  |> justGrandChildMessage
  |> justChildMessage
  |> encodeParentMessage
```

@anmolitor What do you think?

**Comment by anmolitor** [comment]
Hmm. I don't know if piping is the most maintainable and readable pattern here (although I generally like code written in pipeline style).
What happens if you add any more fields to one of the messages? 
You probably have to restructure your code.

I suggest this instead:
```
let
  grandChildMessage = {}
  childMessage = { msg = Just <| GrandChildMessage grandChildMessage }
  parentMessage = { msg = Just <| ChildMessage childMessage }
in encodeParentMessage parentMessage
```
(right now this is not possible in the most recent version due to fromInternal/toInternal functions but it will be in 4.0.0.
I released a beta yesterday)
